/**
 * Deterministic synonyms for catalog names. AI-proposed names are never trusted
 * until they resolve to a registered capability through this map or an exact match.
 */
export const CAPABILITY_ALIASES: Readonly<Record<string, string>> = {
  authentication: 'auth',
  jwt: 'auth',
  login: 'auth',
  'user.auth': 'auth',
  authorization: 'rbac',
  roles: 'rbac',
  permissions: 'rbac',
  'role-based-access': 'rbac',
  postgres: 'infrastructure.postgres',
  postgresql: 'infrastructure.postgres',
  'postgres.db': 'infrastructure.postgres',
  redis: 'infrastructure.redis',
  docker: 'infrastructure.docker',
  compose: 'infrastructure.docker',
  'docker-compose': 'deployment.docker-compose',
  'github-actions': 'infrastructure.github-actions',
  githubactions: 'infrastructure.github-actions',
  ci: 'infrastructure.github-actions',
  cicd: 'infrastructure.github-actions',
  nginx: 'infrastructure.nginx',
  kubernetes: 'deployment.kubernetes',
  k8s: 'deployment.kubernetes',
  microservices: 'architecture.microservices',
  'modular-monolith': 'architecture.modular-monolith',
  monolith: 'architecture.modular-monolith',
  gemini: 'adapter.ai.gemini',
  'ai.mock': 'adapter.ai.mock',
  smtp: 'adapter.email.smtp',
  resend: 'adapter.email.resend',
  brevo: 'adapter.email.brevo',
  s3: 'adapter.storage.s3',
  'local-storage': 'adapter.storage.local',
  llm: 'ai',
  'ai-toolkit': 'ai',
  'ai.toolkit': 'ai',
  summarization: 'ai.summarization',
  'ai.summarize': 'ai.summarization',
  classification: 'ai.classification',
  'ai.classify': 'ai.classification',
  extraction: 'ai.extraction',
  'ai.extract': 'ai.extraction',
  recommendation: 'ai.recommendation',
  'ai.recommend': 'ai.recommendation',
  guardrails: 'ai.guardrails',
  'document-intelligence': 'documents',
  'document.intelligence': 'documents',
  documents: 'documents',
  copilot: 'copilot',
  intents: 'intents',
  rag: 'rag',
  'semantic-search': 'rag',
  search: 'search',
  'keyword-search': 'search',
  'full-text-search': 'search',
  'fulltext-search': 'search',
  'full-text': 'search',
  analytics: 'analytics',
  kpi: 'analytics',
  'time-series': 'analytics',
  timeseries: 'analytics',
  // elasticsearch / opensearch / solr stay unmapped. They are not this catalog's search capability.
  // clickhouse / bigquery / snowflake / redshift stay unmapped. They are not this catalog's analytics capability.
  anomaly: 'anomaly',
  'anomaly-detection': 'anomaly',
  jobs: 'jobs',
  'background-jobs': 'jobs',
  queue: 'jobs',
  bullmq: 'jobs',
  events: 'events',
  'event-bus': 'events',
  automation: 'automation',
  scheduler: 'scheduler',
  notifications: 'notifications',
  email: 'email',
  sms: 'sms',
  otp: 'otp',
  pdf: 'pdf',
  reports: 'reports',
  storage: 'storage',
  webhooks: 'webhooks',
  audit: 'audit',
  observability: 'observability',
  logging: 'observability',
  security: 'security',
  validation: 'validation',
  database: 'database',
  odoo: 'odoo',
  'feature-flags': 'feature-flags',
  'demo-mode': 'demo-mode',
  testing: 'testing',
  foundation: 'foundation',
  'problem-module': 'problem.module',
  'problem.module': 'problem.module',
  'ui-kit': 'frontend.ui',
  ui: 'frontend.ui',
  dashboard: 'frontend.dashboard',
  forms: 'frontend.forms',
  tables: 'frontend.tables',
  charts: 'frontend.charts',
};

export function normalizeCapabilityRef(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[_/]+/g, '.')
    .replace(/\s+/g, '.')
    .replace(/\.+/g, '.')
    .replace(/^\.+|\.+$/g, '');
}
