import { describe, expect, it } from 'vitest';

import { DEFAULT_ROLE_PERMISSIONS, PERMISSIONS, ROLES } from './catalog';

describe('default RBAC catalog', () => {
  it('keeps Odoo writes off application login roles', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.ODOO_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.ODOO_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).toContain(PERMISSIONS.ODOO_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.ODOO_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.ODOO_WRITE);
  });

  it('does not grant ADMIN through a wildcard — only listed keys', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.ADMIN_SETTINGS);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).not.toContain('inventory.approve');
  });

  it('grants document intelligence to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.DOCUMENTS_ANALYZE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.DOCUMENTS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.DOCUMENTS_ANALYZE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.DOCUMENTS_ANALYZE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.DOCUMENTS_READ);
  });

  it('grants copilot.use to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.COPILOT_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.COPILOT_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.COPILOT_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.COPILOT_USE);
  });

  it('grants anomaly.use to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.ANOMALY_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.ANOMALY_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.ANOMALY_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.ANOMALY_USE);
  });

  it('grants search.use to staff, manager, and admin; search.write to manager and admin', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.SEARCH_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.SEARCH_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.SEARCH_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.SEARCH_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).toContain(PERMISSIONS.SEARCH_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.SEARCH_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.SEARCH_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.SEARCH_WRITE);
  });

  it('grants analytics.read to staff, manager, and admin; write/export to manager and admin', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.ANALYTICS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.ANALYTICS_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.ANALYTICS_EXPORT);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.ANALYTICS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).toContain(PERMISSIONS.ANALYTICS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.ANALYTICS_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.ANALYTICS_EXPORT);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.ANALYTICS_READ);
  });

  it('grants rag.use to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.RAG_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.RAG_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.RAG_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.RAG_USE);
  });

  it('grants intents.use to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.INTENTS_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.INTENTS_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.INTENTS_USE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.INTENTS_USE);
  });

  it('grants problem.analyze to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.PROBLEM_ANALYZE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.PROBLEM_ANALYZE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.PROBLEM_ANALYZE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.PROBLEM_ANALYZE);
  });

  it('grants capabilities.recommend to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.CAPABILITIES_RECOMMEND);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.CAPABILITIES_RECOMMEND);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.CAPABILITIES_RECOMMEND);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.CAPABILITIES_RECOMMEND);
  });

  it('grants projects.plan to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.PROJECTS_PLAN);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.PROJECTS_PLAN);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.PROJECTS_PLAN);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.PROJECTS_PLAN);
  });

  it('grants projects.generate to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.PROJECTS_GENERATE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.PROJECTS_GENERATE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.PROJECTS_GENERATE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.PROJECTS_GENERATE);
  });

  it('grants automation write/execute to manager and admin; staff can read', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.AUTOMATIONS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.AUTOMATIONS_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.AUTOMATIONS_EXECUTE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.AUTOMATIONS_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).toContain(PERMISSIONS.AUTOMATIONS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.AUTOMATIONS_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.AUTOMATIONS_READ);
  });

  it('grants files.read and files.write to user, staff, manager, and admin', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).toContain(PERMISSIONS.FILES_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).toContain(PERMISSIONS.FILES_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).toContain(PERMISSIONS.FILES_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.FILES_WRITE);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.FILES_WRITE);
  });

  it('grants jobs.read to staff, manager, and admin', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).toContain(PERMISSIONS.JOBS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.JOBS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.JOBS_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.JOBS_READ);
  });

  it('grants audit.read to manager and admin, not staff or user', () => {
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.MANAGER]).toContain(PERMISSIONS.AUDIT_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.ADMIN]).toContain(PERMISSIONS.AUDIT_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.STAFF]).not.toContain(PERMISSIONS.AUDIT_READ);
    expect(DEFAULT_ROLE_PERMISSIONS[ROLES.USER]).not.toContain(PERMISSIONS.AUDIT_READ);
  });
});
