import { defineCapability } from './define';

export const ADAPTER_CAPABILITIES = [
  defineCapability({
    name: 'adapter.ai.gemini',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Gemini REST provider behind AIService. Credentials stay server-side.',
    dependencies: ['ai'],
    environmentRequirements: ['AI_PROVIDER', 'GEMINI_API_KEY'],
    providerRequirements: ['gemini'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/ai/providers/gemini.provider.test.ts'],
    documentation: ['docs/ai.md'],
  }),
  defineCapability({
    name: 'adapter.ai.mock',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'In-process mock AI provider for tests and demo mode.',
    dependencies: ['ai'],
    environmentRequirements: ['AI_PROVIDER'],
    providerRequirements: ['mock'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/ai/ai.service.test.ts'],
    documentation: ['docs/ai.md'],
  }),
  defineCapability({
    name: 'adapter.email.smtp',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Nodemailer SMTP email provider.',
    dependencies: ['email'],
    environmentRequirements: ['EMAIL_PROVIDER', 'SMTP_HOST'],
    providerRequirements: ['smtp'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/email/email.providers.test.ts'],
    documentation: ['docs/email.md'],
  }),
  defineCapability({
    name: 'adapter.email.resend',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Resend HTTP email provider.',
    dependencies: ['email'],
    environmentRequirements: ['EMAIL_PROVIDER', 'RESEND_API_KEY'],
    providerRequirements: ['resend'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/email/email.providers.test.ts'],
    documentation: ['docs/email.md'],
  }),
  defineCapability({
    name: 'adapter.email.brevo',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Brevo HTTP email provider.',
    dependencies: ['email'],
    environmentRequirements: ['EMAIL_PROVIDER', 'BREVO_API_KEY'],
    providerRequirements: ['brevo'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/email/email.providers.test.ts'],
    documentation: ['docs/email.md'],
  }),
  defineCapability({
    name: 'adapter.email.mock',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'In-process mock email provider. Demo mode never delivers real mail.',
    dependencies: ['email'],
    environmentRequirements: ['EMAIL_PROVIDER'],
    providerRequirements: ['mock'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/email/email.providers.test.ts'],
    documentation: ['docs/email.md'],
  }),
  defineCapability({
    name: 'adapter.sms.http',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Generic HTTP SMS gateway adapter.',
    dependencies: ['sms'],
    environmentRequirements: ['SMS_PROVIDER', 'SMS_HTTP_URL', 'SMS_API_KEY'],
    providerRequirements: ['http'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/sms/sms.service.test.ts'],
    documentation: ['docs/sms.md'],
  }),
  defineCapability({
    name: 'adapter.sms.mock',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'In-process mock SMS provider. Demo mode never hits a real gateway.',
    dependencies: ['sms'],
    environmentRequirements: ['SMS_PROVIDER'],
    providerRequirements: ['mock'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/sms/sms.service.test.ts'],
    documentation: ['docs/sms.md'],
  }),
  defineCapability({
    name: 'adapter.storage.local',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Local filesystem object storage. Dual-writes to Postgres when a database is configured.',
    dependencies: ['storage'],
    environmentRequirements: ['STORAGE_PROVIDER'],
    providerRequirements: ['local'],
    tests: ['backend/src/integrations/storage/storage.service.test.ts'],
    documentation: ['docs/storage.md'],
  }),
  defineCapability({
    name: 'adapter.storage.postgres',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'PostgreSQL object rows for multi-host file sharing.',
    dependencies: ['storage', 'infrastructure.postgres'],
    environmentRequirements: ['STORAGE_PROVIDER', 'DATABASE_URL'],
    providerRequirements: ['postgres'],
    defaultEnabled: false,
    databaseRequirement: true,
    tests: ['backend/src/integrations/storage/storage.service.test.ts'],
    documentation: ['docs/storage.md'],
  }),
  defineCapability({
    name: 'adapter.storage.s3',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'AWS S3 object storage. FEATURE_S3 or STORAGE_PROVIDER=s3.',
    dependencies: ['storage'],
    environmentRequirements: [
      'FEATURE_S3',
      'STORAGE_PROVIDER',
      'AWS_ACCESS_KEY_ID',
      'AWS_SECRET_ACCESS_KEY',
      'AWS_S3_BUCKET',
    ],
    providerRequirements: ['s3'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/storage/storage.service.test.ts'],
    documentation: ['docs/storage.md'],
  }),
  defineCapability({
    name: 'adapter.odoo.json2',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Odoo 19 JSON-2 HTTP adapter. There is no XML-RPC fallback.',
    dependencies: ['odoo'],
    environmentRequirements: ['ODOO_BASE_URL', 'ODOO_DATABASE', 'ODOO_API_KEY'],
    providerRequirements: ['json2'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/odoo/odoo.client.test.ts'],
    documentation: ['docs/odoo.md'],
  }),
  defineCapability({
    name: 'adapter.otp.mock',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Mock OTP delivery adapter used in tests and demo mode.',
    dependencies: ['otp'],
    providerRequirements: ['mock'],
    defaultEnabled: false,
    tests: ['backend/src/otp/otp.service.test.ts'],
    documentation: ['docs/otp.md'],
  }),
  defineCapability({
    name: 'adapter.rag.vector.memory',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'In-memory vector store for RAG. Default for tests.',
    dependencies: ['rag'],
    environmentRequirements: ['RAG_VECTOR_STORE'],
    providerRequirements: ['memory'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/rag/rag.service.test.ts'],
    documentation: ['docs/rag.md'],
  }),
  defineCapability({
    name: 'adapter.rag.vector.postgres',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'PostgreSQL JSON embedding store. Not pgvector.',
    dependencies: ['rag', 'infrastructure.postgres'],
    environmentRequirements: ['RAG_VECTOR_STORE', 'DATABASE_URL'],
    providerRequirements: ['postgres'],
    defaultEnabled: false,
    databaseRequirement: true,
    tests: ['backend/src/integrations/rag/stores/postgres.store.test.ts'],
    documentation: ['docs/rag.md'],
  }),
  defineCapability({
    name: 'adapter.rag.embedding.lexical',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Lexical embedding fallback used when the AI provider is mock.',
    dependencies: ['rag'],
    providerRequirements: ['lexical'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/rag/rag.service.test.ts'],
    documentation: ['docs/rag.md'],
  }),
  defineCapability({
    name: 'adapter.rag.embedding.ai',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'AIService-backed embeddings for RAG.',
    dependencies: ['rag', 'ai'],
    providerRequirements: ['ai'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/rag/rag.service.test.ts'],
    documentation: ['docs/rag.md'],
  }),
  defineCapability({
    name: 'adapter.search.postgres',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'PostgreSQL full-text, keyword, filter, and pg_trgm fuzzy search behind SearchService.',
    dependencies: ['search', 'infrastructure.postgres'],
    environmentRequirements: ['SEARCH_PROVIDER', 'DATABASE_URL'],
    providerRequirements: ['postgres'],
    defaultEnabled: false,
    databaseRequirement: true,
    tests: ['backend/tests/search.db.test.ts'],
    documentation: ['docs/search.md'],
  }),
  defineCapability({
    name: 'adapter.search.memory',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'In-memory search provider for tests and processes without a database.',
    dependencies: ['search'],
    environmentRequirements: ['SEARCH_PROVIDER'],
    providerRequirements: ['memory'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/search/search.service.test.ts'],
    documentation: ['docs/search.md'],
  }),
  defineCapability({
    name: 'adapter.analytics.postgres',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'PostgreSQL indexed fact aggregations and time-series behind AnalyticsService.',
    dependencies: ['analytics', 'infrastructure.postgres'],
    environmentRequirements: ['ANALYTICS_PROVIDER', 'DATABASE_URL'],
    providerRequirements: ['postgres'],
    defaultEnabled: false,
    databaseRequirement: true,
    tests: ['backend/tests/analytics.db.test.ts'],
    documentation: ['docs/analytics.md'],
  }),
  defineCapability({
    name: 'adapter.analytics.memory',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'In-memory analytics provider for tests and processes without a database.',
    dependencies: ['analytics'],
    environmentRequirements: ['ANALYTICS_PROVIDER'],
    providerRequirements: ['memory'],
    defaultEnabled: false,
    tests: ['backend/src/integrations/analytics/analytics.service.test.ts'],
    documentation: ['docs/analytics.md'],
  }),
  defineCapability({
    name: 'adapter.push.mock',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'Mock push channel. Real FCM/APNs is not implemented.',
    dependencies: ['notifications'],
    providerRequirements: ['mock'],
    defaultEnabled: true,
    tests: ['backend/src/notifications/notification.service.test.ts'],
    documentation: ['docs/notifications.md'],
  }),
  defineCapability({
    name: 'adapter.webhook.http',
    kind: 'adapter',
    category: 'adapter',
    maturity: 'stable',
    summary: 'HTTP webhook notification adapter with SSRF checks on user-controlled URLs.',
    dependencies: ['webhooks'],
    providerRequirements: ['http'],
    defaultEnabled: true,
    tests: ['backend/src/security/ssrf.test.ts'],
    documentation: ['docs/notifications.md', 'docs/security.md'],
  }),
];
