import { PERMISSIONS } from '../../rbac/catalog';
import { defineCapability } from './define';

export const APPLICATION_CAPABILITIES = [
  defineCapability({
    name: 'foundation',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Configuration, API conventions, health/readiness, and graceful shutdown.',
    tests: ['backend/src/config/config.test.ts', 'backend/src/services/health.service.test.ts'],
    documentation: ['docs/foundation.md', 'docs/configuration.md'],
  }),
  defineCapability({
    name: 'validation',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Shared Zod parse helpers and normalized AppError types.',
    tests: ['backend/src/schemas/parse.test.ts', 'backend/src/errors/app-error.test.ts'],
    documentation: ['docs/validation.md', 'docs/api-conventions.md'],
  }),
  defineCapability({
    name: 'security',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Helmet, CORS, rate limits, CSRF cookies, SSRF checks, and secret scanning.',
    tests: [
      'backend/src/security/csrf.test.ts',
      'backend/src/security/ssrf.test.ts',
      'backend/src/security/trust-proxy.test.ts',
    ],
    documentation: ['docs/security.md'],
  }),
  defineCapability({
    name: 'database',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'PostgreSQL persistence through Prisma repositories and migrations.',
    dependencies: ['infrastructure.postgres'],
    infrastructureRequirements: ['postgres'],
    environmentRequirements: ['DATABASE_URL'],
    databaseRequirement: true,
    tests: ['backend/src/repositories/query/pagination.test.ts'],
    documentation: ['docs/database.md'],
  }),
  defineCapability({
    name: 'auth',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Register, login, JWT access/refresh, optional cookies, and password reset.',
    dependencies: ['database'],
    optionalDependencies: ['otp', 'infrastructure.redis'],
    environmentRequirements: ['JWT_ACCESS_SECRET', 'JWT_REFRESH_SECRET'],
    permissions: [PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE],
    databaseRequirement: true,
    frontendAvailability: true,
    tests: ['backend/src/auth/auth.test.ts', 'backend/src/auth/jwt.test.ts'],
    documentation: ['docs/auth.md'],
  }),
  defineCapability({
    name: 'rbac',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'User → Role → Permission with authorizeRole and requirePermission.',
    dependencies: ['auth', 'database'],
    permissions: [PERMISSIONS.ROLES_READ, PERMISSIONS.ROLES_WRITE],
    databaseRequirement: true,
    tests: ['backend/src/rbac/authorize.test.ts', 'backend/src/rbac/catalog.test.ts'],
    documentation: ['docs/rbac.md'],
  }),
  defineCapability({
    name: 'audit',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Redacted audit_events and GET /api/v1/audit.',
    dependencies: ['database'],
    permissions: [PERMISSIONS.AUDIT_READ],
    databaseRequirement: true,
    tests: ['backend/src/audit/audit.service.test.ts'],
    documentation: ['docs/audit.md'],
  }),
  defineCapability({
    name: 'observability',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Structured logs, health/readiness, and optional metrics/error-tracking hooks.',
    tests: ['backend/src/observability/observability.test.ts', 'backend/src/utils/logger.test.ts'],
    documentation: ['docs/observability.md'],
  }),
  defineCapability({
    name: 'testing',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Vitest unit/HTTP/DB suites, factories, mocks, and CI without paid APIs.',
    frontendAvailability: true,
    tests: ['backend/src/config/config.test.ts'],
    documentation: ['docs/testing.md'],
  }),
  defineCapability({
    name: 'feature-flags',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Env FEATURE_* registry and GET /api/v1/features. Not a remote flag SaaS.',
    frontendAvailability: true,
    tests: ['backend/src/features/features.test.ts'],
    documentation: ['docs/features.md'],
  }),
  defineCapability({
    name: 'demo-mode',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Safe demo defaults: mock email/SMS/OTP, optional mock AI. Production refuses it unless allowed.',
    environmentRequirements: ['DEMO_MODE'],
    defaultEnabled: true,
    tests: ['backend/src/features/features.test.ts'],
    documentation: ['docs/features.md'],
  }),
  defineCapability({
    name: 'jobs',
    kind: 'application',
    category: 'automation',
    maturity: 'stable',
    summary: 'In-memory, file, or BullMQ queues with status API, retries, and timeouts.',
    optionalDependencies: ['infrastructure.redis'],
    environmentRequirements: ['REDIS_URL', 'JOB_MAX_ATTEMPTS', 'JOB_TIMEOUT_MS'],
    permissions: [PERMISSIONS.JOBS_READ],
    workerRequirement: true,
    tests: ['backend/src/jobs/queue.test.ts', 'backend/src/jobs/retry.test.ts'],
    documentation: ['docs/jobs.md'],
  }),
  defineCapability({
    name: 'events',
    kind: 'application',
    category: 'automation',
    maturity: 'stable',
    summary: 'In-process EventBus. Cross-process work uses the job queue, not this bus.',
    tests: ['backend/src/events/event-bus.test.ts'],
    documentation: ['docs/automation.md'],
  }),
  defineCapability({
    name: 'scheduler',
    kind: 'application',
    category: 'automation',
    maturity: 'stable',
    summary: 'Interval and UTC cron ticks that emit scheduled events on the API process.',
    dependencies: ['events'],
    optionalDependencies: ['automation', 'infrastructure.redis'],
    environmentRequirements: ['SCHEDULER_ENABLED'],
    tests: ['backend/src/scheduler/scheduler.test.ts', 'backend/src/scheduler/cron.test.ts'],
    documentation: ['docs/scheduler.md'],
  }),
  defineCapability({
    name: 'automation',
    kind: 'application',
    category: 'automation',
    maturity: 'stable',
    summary: 'Declarative trigger-condition-action workflows. No JavaScript conditions.',
    dependencies: ['events', 'jobs'],
    optionalDependencies: ['email', 'notifications', 'odoo', 'ai', 'pdf'],
    environmentRequirements: ['FEATURE_AUTOMATION'],
    permissions: [
      PERMISSIONS.AUTOMATIONS_READ,
      PERMISSIONS.AUTOMATIONS_WRITE,
      PERMISSIONS.AUTOMATIONS_EXECUTE,
    ],
    featureFlag: 'automation',
    defaultEnabled: false,
    databaseRequirement: true,
    workerRequirement: true,
    frontendAvailability: true,
    tests: ['backend/src/automation/automation.service.test.ts'],
    documentation: ['docs/automation.md'],
  }),
  defineCapability({
    name: 'notifications',
    kind: 'application',
    category: 'automation',
    maturity: 'stable',
    summary:
      'Multi-channel notification engine. Inbox HTTP stays available with a database; FEATURE_NOTIFICATIONS gates extra side effects.',
    optionalDependencies: ['email', 'sms', 'jobs', 'database'],
    environmentRequirements: ['FEATURE_NOTIFICATIONS'],
    permissions: [PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_WRITE],
    databaseRequirement: true,
    workerRequirement: true,
    frontendAvailability: true,
    tests: ['backend/src/notifications/notification.service.test.ts'],
    documentation: ['docs/notifications.md'],
  }),
  defineCapability({
    name: 'storage',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary: 'Validated uploads and signed downloads via local, PostgreSQL, or S3 adapters.',
    optionalDependencies: ['adapter.storage.s3', 'adapter.storage.postgres', 'database'],
    environmentRequirements: ['STORAGE_PROVIDER', 'STORAGE_SIGNING_SECRET'],
    permissions: [PERMISSIONS.FILES_READ, PERMISSIONS.FILES_WRITE],
    providerRequirements: ['local'],
    tests: [
      'backend/src/integrations/storage/storage.service.test.ts',
      'backend/src/integrations/storage/storage.sign.test.ts',
    ],
    documentation: ['docs/storage.md'],
  }),
  defineCapability({
    name: 'email',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary: 'Transactional email through SMTP, Resend, Brevo, or mock providers.',
    optionalDependencies: ['jobs', 'ai'],
    environmentRequirements: ['EMAIL_ENABLED', 'EMAIL_PROVIDER', 'EMAIL_FROM'],
    providerRequirements: ['smtp', 'resend', 'brevo', 'mock'],
    workerRequirement: true,
    tests: [
      'backend/src/integrations/email/email.service.test.ts',
      'backend/src/integrations/email/email.providers.test.ts',
    ],
    documentation: ['docs/email.md'],
  }),
  defineCapability({
    name: 'sms',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary: 'Transactional SMS through mock or generic HTTP providers.',
    optionalDependencies: ['jobs'],
    environmentRequirements: ['FEATURE_SMS', 'SMS_PROVIDER'],
    providerRequirements: ['mock', 'http'],
    featureFlag: 'sms',
    defaultEnabled: false,
    workerRequirement: true,
    tests: ['backend/src/integrations/sms/sms.service.test.ts'],
    documentation: ['docs/sms.md'],
  }),
  defineCapability({
    name: 'otp',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary: 'Hashed one-time passcodes with email, SMS, or mock delivery.',
    optionalDependencies: ['email', 'sms', 'infrastructure.redis'],
    environmentRequirements: ['FEATURE_OTP', 'OTP_HASH_SECRET'],
    featureFlag: 'otp',
    defaultEnabled: false,
    tests: ['backend/src/otp/otp.service.test.ts'],
    documentation: ['docs/otp.md'],
  }),
  defineCapability({
    name: 'pdf',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary: 'PDF renderer plus generate HTTP. FEATURE_PDF gates HTTP; jobs can still render.',
    optionalDependencies: ['storage', 'jobs'],
    environmentRequirements: ['FEATURE_PDF'],
    featureFlag: 'pdf',
    defaultEnabled: true,
    workerRequirement: true,
    tests: [
      'backend/src/integrations/pdf/pdf.service.test.ts',
      'backend/src/integrations/pdf/pdf.renderer.test.ts',
    ],
    documentation: ['docs/pdf.md'],
  }),
  defineCapability({
    name: 'reports',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary: 'Pluggable report templates, async PDF jobs, and optional notification/email.',
    dependencies: ['pdf', 'storage'],
    optionalDependencies: ['jobs', 'notifications', 'email'],
    permissions: [PERMISSIONS.REPORTS_GENERATE],
    workerRequirement: true,
    tests: ['backend/src/integrations/pdf/pdf.service.test.ts'],
    documentation: ['docs/reports.md'],
  }),
  defineCapability({
    name: 'webhooks',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary: 'Notification webhook channel and automation inbound webhooks.',
    optionalDependencies: ['notifications', 'automation'],
    tests: ['backend/src/notifications/notification.service.test.ts'],
    documentation: ['docs/notifications.md', 'docs/automation.md'],
  }),
  defineCapability({
    name: 'search',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary:
      'Provider-agnostic keyword, filter, sort, pagination, and PostgreSQL full-text search. Fuzzy matching uses pg_trgm for short typed queries. Elasticsearch is not shipped; SearchProvider allows a future adapter.',
    dependencies: ['database'],
    optionalDependencies: ['adapter.search.postgres', 'adapter.search.memory'],
    environmentRequirements: ['FEATURE_SEARCH', 'SEARCH_PROVIDER'],
    permissions: [PERMISSIONS.SEARCH_USE, PERMISSIONS.SEARCH_WRITE],
    featureFlag: 'search',
    defaultEnabled: false,
    databaseRequirement: true,
    frontendAvailability: true,
    tests: [
      'backend/src/integrations/search/search.service.test.ts',
      'backend/tests/search.http.test.ts',
      'backend/tests/search.db.test.ts',
    ],
    documentation: ['docs/search.md'],
  }),
  defineCapability({
    name: 'analytics',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary:
      'Reusable KPI definitions, aggregations, time-series queries, dashboards, filters, and exports. Problem-specific metrics are registered from modules/problem. Not a warehouse.',
    dependencies: ['database'],
    optionalDependencies: ['adapter.analytics.postgres', 'adapter.analytics.memory'],
    environmentRequirements: ['FEATURE_ANALYTICS', 'ANALYTICS_PROVIDER'],
    permissions: [PERMISSIONS.ANALYTICS_READ, PERMISSIONS.ANALYTICS_WRITE, PERMISSIONS.ANALYTICS_EXPORT],
    featureFlag: 'analytics',
    defaultEnabled: false,
    databaseRequirement: true,
    frontendAvailability: true,
    tests: [
      'backend/src/integrations/analytics/analytics.service.test.ts',
      'backend/tests/analytics.http.test.ts',
      'backend/tests/analytics.db.test.ts',
    ],
    documentation: ['docs/analytics.md'],
  }),
  defineCapability({
    name: 'odoo',
    kind: 'application',
    category: 'integration',
    maturity: 'stable',
    summary:
      'Odoo 19 JSON-2 client, operations, and OdooCapabilityRegistry allowlist. Not this platform catalog.',
    environmentRequirements: ['FEATURE_ODOO', 'ODOO_BASE_URL', 'ODOO_DATABASE', 'ODOO_API_KEY'],
    providerRequirements: ['json2'],
    permissions: [PERMISSIONS.ODOO_READ, PERMISSIONS.ODOO_WRITE],
    featureFlag: 'odoo',
    defaultEnabled: false,
    workerRequirement: true,
    tests: [
      'backend/src/integrations/odoo/odoo.service.test.ts',
      'backend/src/integrations/odoo/odoo.client.test.ts',
    ],
    documentation: ['docs/odoo.md'],
  }),
  defineCapability({
    name: 'ai',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Provider-agnostic AIService (Gemini or mock) with schema-validated structured output.',
    environmentRequirements: ['FEATURE_AI', 'AI_PROVIDER', 'GEMINI_API_KEY'],
    providerRequirements: ['gemini', 'mock'],
    permissions: [PERMISSIONS.AI_USE],
    featureFlag: 'ai',
    defaultEnabled: false,
    workerRequirement: true,
    tests: [
      'backend/src/integrations/ai/ai.service.test.ts',
      'backend/src/integrations/ai/ai.schemas.test.ts',
    ],
    documentation: ['docs/ai.md'],
  }),
  defineCapability({
    name: 'ai.guardrails',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Input limits, output schema, redaction, tool allowlisting, confirmation, and AI audit.',
    dependencies: ['ai'],
    optionalDependencies: ['rbac', 'audit'],
    featureFlag: 'ai',
    defaultEnabled: false,
    tests: ['backend/src/integrations/ai/guardrails/guardrails.test.ts'],
    documentation: ['docs/ai-guardrails.md'],
  }),
  defineCapability({
    name: 'ai.summarization',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Summarize text into summary, key points, and actions via AIService.summarize.',
    dependencies: ['ai', 'ai.guardrails'],
    featureFlag: 'ai',
    defaultEnabled: false,
    tests: ['backend/src/integrations/ai/ai.service.test.ts'],
    documentation: ['docs/ai.md'],
  }),
  defineCapability({
    name: 'ai.classification',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Category, priority, sentiment, and confidence via AIService.classify.',
    dependencies: ['ai', 'ai.guardrails'],
    featureFlag: 'ai',
    defaultEnabled: false,
    tests: ['backend/src/integrations/ai/ai.service.test.ts'],
    documentation: ['docs/ai.md'],
  }),
  defineCapability({
    name: 'ai.extraction',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Fields, entities, and action items via AIService.extract.',
    dependencies: ['ai', 'ai.guardrails'],
    featureFlag: 'ai',
    defaultEnabled: false,
    tests: ['backend/src/integrations/ai/ai.service.test.ts'],
    documentation: ['docs/ai.md'],
  }),
  defineCapability({
    name: 'ai.recommendation',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Suggestion, reason, evidence, and confidence via AIService.recommend.',
    dependencies: ['ai', 'ai.guardrails'],
    featureFlag: 'ai',
    defaultEnabled: false,
    tests: ['backend/src/integrations/ai/ai.service.test.ts'],
    documentation: ['docs/ai.md'],
  }),
  defineCapability({
    name: 'documents',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Upload, store, extract, and persist document intelligence separately from AI output.',
    dependencies: ['ai', 'ai.guardrails', 'storage'],
    optionalDependencies: ['jobs', 'notifications'],
    permissions: [PERMISSIONS.DOCUMENTS_ANALYZE, PERMISSIONS.DOCUMENTS_READ],
    featureFlag: 'ai',
    defaultEnabled: false,
    databaseRequirement: true,
    workerRequirement: true,
    tests: [
      'backend/src/integrations/documents/document.service.test.ts',
      'backend/src/integrations/documents/document.review.test.ts',
    ],
    documentation: ['docs/documents.md'],
  }),
  defineCapability({
    name: 'copilot',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Allowlisted copilot tools, planner, confirmation, and chat UI. Not AND-gated with FEATURE_AI.',
    dependencies: ['ai', 'ai.guardrails'],
    optionalDependencies: ['rbac', 'database'],
    environmentRequirements: ['FEATURE_COPILOT'],
    permissions: [PERMISSIONS.COPILOT_USE],
    featureFlag: 'copilot',
    defaultEnabled: false,
    databaseRequirement: true,
    frontendAvailability: true,
    tests: ['backend/src/copilot/copilot.service.test.ts'],
    documentation: ['docs/copilot.md'],
  }),
  defineCapability({
    name: 'intents',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Natural language → registered intent → validate → authorize → confirm → handler.',
    dependencies: ['ai', 'ai.guardrails'],
    environmentRequirements: ['FEATURE_INTENTS'],
    permissions: [PERMISSIONS.INTENTS_USE],
    featureFlag: 'intents',
    defaultEnabled: false,
    frontendAvailability: true,
    tests: [
      'backend/src/intents/intents.service.test.ts',
      'backend/src/intents/intents.pending.test.ts',
    ],
    documentation: ['docs/intents.md'],
  }),
  defineCapability({
    name: 'rag',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Optional semantic search with source citations. Off unless FEATURE_RAG is set.',
    dependencies: ['ai', 'ai.guardrails'],
    optionalDependencies: ['database'],
    environmentRequirements: ['FEATURE_RAG'],
    permissions: [PERMISSIONS.RAG_USE],
    featureFlag: 'rag',
    defaultEnabled: false,
    workerRequirement: true,
    frontendAvailability: true,
    tests: [
      'backend/src/integrations/rag/rag.service.test.ts',
      'backend/src/integrations/rag/rag.grounding.test.ts',
    ],
    documentation: ['docs/rag.md'],
  }),
  defineCapability({
    name: 'realtime',
    kind: 'application',
    category: 'automation',
    maturity: 'stable',
    summary:
      'Optional Server-Sent Events for allowlisted job, notification, dashboard, automation, and document status. Not WebSockets. REST polling stays available when the flag is off.',
    optionalDependencies: ['jobs', 'events', 'notifications', 'automation', 'documents', 'infrastructure.redis'],
    environmentRequirements: ['FEATURE_REALTIME'],
    permissions: [PERMISSIONS.JOBS_READ, PERMISSIONS.NOTIFICATIONS_READ],
    featureFlag: 'realtime',
    defaultEnabled: false,
    frontendAvailability: true,
    tests: [
      'backend/src/realtime/realtime.hub.test.ts',
      'backend/src/realtime/realtime.service.test.ts',
      'backend/tests/realtime.http.test.ts',
    ],
    documentation: ['docs/realtime.md'],
  }),
  defineCapability({
    name: 'anomaly',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary: 'Statistical detectors plus optional AI explanation. Detection does not require AI.',
    optionalDependencies: ['ai', 'events', 'notifications'],
    environmentRequirements: ['FEATURE_ANOMALY_DETECTION'],
    permissions: [PERMISSIONS.ANOMALY_USE],
    featureFlag: 'anomalyDetection',
    defaultEnabled: false,
    workerRequirement: true,
    frontendAvailability: true,
    tests: [
      'backend/src/anomaly/anomaly.service.test.ts',
      'backend/src/anomaly/anomaly.detectors.test.ts',
    ],
    documentation: ['docs/anomaly.md'],
  }),
  defineCapability({
    name: 'problem.module',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary: 'Isolated @hackathon/problem extension loaded at runtime by the API and worker.',
    tests: [
      'backend/src/problem/register.test.ts',
      'backend/src/problem/load.test.ts',
      'backend/tests/problem.http.test.ts',
    ],
    documentation: ['docs/problem-module.md', 'modules/problem/README.md'],
    frontendAvailability: true,
  }),
  defineCapability({
    name: 'problem.intelligence',
    kind: 'application',
    category: 'ai',
    maturity: 'stable',
    summary:
      'Convert a problem statement into a structured spec and classify each requirement as an existing capability or new problem logic. AI output is untrusted; the catalog is authoritative.',
    dependencies: ['ai', 'ai.guardrails'],
    optionalDependencies: ['audit', 'rbac'],
    environmentRequirements: ['FEATURE_PROBLEM_INTELLIGENCE'],
    permissions: [PERMISSIONS.PROBLEM_ANALYZE],
    featureFlag: 'problemIntelligence',
    defaultEnabled: false,
    frontendAvailability: true,
    tests: [
      'backend/src/problem-intelligence/service.test.ts',
      'backend/src/problem-intelligence/classify.test.ts',
      'backend/tests/problem-intelligence.http.test.ts',
    ],
    documentation: ['docs/problem-intelligence.md'],
  }),
  defineCapability({
    name: 'capability.recommendations',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary:
      'Deterministic advisory mapping from structured problem analysis to capabilities, profiles, adapters, infrastructure, and architecture/deployment modes. Never enables FEATURE_* or constructs services.',
    optionalDependencies: ['problem.intelligence', 'audit', 'rbac'],
    environmentRequirements: ['FEATURE_CAPABILITY_RECOMMENDATIONS'],
    permissions: [PERMISSIONS.CAPABILITIES_RECOMMEND],
    featureFlag: 'capabilityRecommendations',
    defaultEnabled: false,
    frontendAvailability: true,
    tests: [
      'backend/src/capability-recommendations/engine.test.ts',
      'backend/src/capability-recommendations/service.test.ts',
      'backend/tests/capability-recommendations.http.test.ts',
    ],
    documentation: ['docs/capability-recommendations.md'],
  }),
  defineCapability({
    name: 'project.planning',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary:
      'Human-driven project planning: problem statement, extracted requirements, capability selection, and a backend-validated Project Configuration. Does not generate code or enable FEATURE_*.',
    optionalDependencies: ['problem.intelligence', 'capability.recommendations', 'audit', 'rbac'],
    environmentRequirements: ['FEATURE_PROJECT_PLANNING'],
    permissions: [PERMISSIONS.PROJECTS_PLAN],
    featureFlag: 'projectPlanning',
    defaultEnabled: false,
    frontendAvailability: true,
    tests: [
      'backend/src/project-planning/engine.test.ts',
      'backend/src/project-planning/service.test.ts',
      'backend/tests/project-planning.http.test.ts',
    ],
    documentation: ['docs/project-planning.md'],
  }),
  defineCapability({
    name: 'project.generator',
    kind: 'application',
    category: 'core',
    maturity: 'stable',
    summary:
      'Deterministic project generator. Consumes an approved Project Configuration and writes an isolated overlay (core + selected capabilities + adapters + problem module + tests + docs). Does not modify kit source or provider internals.',
    optionalDependencies: ['project.planning', 'audit', 'rbac'],
    environmentRequirements: ['FEATURE_PROJECT_GENERATOR'],
    permissions: [PERMISSIONS.PROJECTS_GENERATE],
    featureFlag: 'projectGenerator',
    defaultEnabled: false,
    frontendAvailability: true,
    tests: [
      'backend/src/project-generator/engine.test.ts',
      'backend/src/project-generator/service.test.ts',
      'backend/tests/project-generator.http.test.ts',
    ],
    documentation: ['docs/project-generator.md'],
  }),
];
