import { defineCapability } from './define';

export const FRONTEND_CAPABILITIES = [
  defineCapability({
    name: 'frontend.ui',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Reusable primitives, overlays, and visual building blocks.',
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/primitives/primitives.test.tsx', 'frontend/src/ui/overlays/overlays.test.tsx'],
    documentation: ['docs/ui.md'],
  }),
  defineCapability({
    name: 'frontend.layout',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'App shell, sidebar, topbar, page container, and grid.',
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/layout/layout.test.tsx'],
    documentation: ['docs/ui.md'],
  }),
  defineCapability({
    name: 'frontend.dashboard',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Slot-based KPI/chart/activity/table layout with no hardcoded business data.',
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/dashboard/SimpleCharts.test.tsx'],
    documentation: ['docs/ui.md'],
  }),
  defineCapability({
    name: 'frontend.forms',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Labeled inputs, select, checkbox, and radio.',
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/primitives/primitives.test.tsx'],
    documentation: ['docs/ui.md'],
  }),
  defineCapability({
    name: 'frontend.tables',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Generic data table and pagination.',
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/data/data.test.tsx'],
    documentation: ['docs/ui.md'],
  }),
  defineCapability({
    name: 'frontend.charts',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'SVG bar and line charts plus a chart-area slot.',
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/dashboard/SimpleCharts.test.tsx'],
    documentation: ['docs/ui.md'],
  }),
  defineCapability({
    name: 'frontend.auth',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Login form, session provider, and sign-in page.',
    dependencies: ['auth'],
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/auth/LoginForm.test.tsx', 'frontend/src/auth/AuthProvider.test.tsx'],
    documentation: ['docs/ui.md', 'docs/auth.md'],
  }),
  defineCapability({
    name: 'frontend.notifications',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'In-app inbox, preferences, and bell UI.',
    dependencies: ['notifications'],
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/NotificationsPage.test.tsx', 'frontend/src/components/NotificationList.test.tsx'],
    documentation: ['docs/ui.md', 'docs/notifications.md'],
  }),
  defineCapability({
    name: 'frontend.ai',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'AI result surfaces: evidence, confidence, and loading states.',
    optionalDependencies: ['ai'],
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/gallery.test.tsx'],
    documentation: ['docs/ui.md', 'docs/ai.md'],
  }),
  defineCapability({
    name: 'frontend.copilot',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Copilot chat UI. Nav is gated by FEATURE_COPILOT (UX only).',
    dependencies: ['copilot'],
    featureFlag: 'copilot',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/components/CopilotChat.test.tsx'],
    documentation: ['docs/ui.md', 'docs/copilot.md'],
  }),
  defineCapability({
    name: 'frontend.problem-intelligence',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Problem-statement analysis UI. Nav is gated by FEATURE_PROBLEM_INTELLIGENCE (UX only).',
    dependencies: ['problem.intelligence'],
    featureFlag: 'problemIntelligence',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/ProblemIntelligencePage.test.tsx'],
    documentation: ['docs/ui.md', 'docs/problem-intelligence.md'],
  }),
  defineCapability({
    name: 'frontend.capability-recommendations',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Capability recommendation UI. Nav is gated by FEATURE_CAPABILITY_RECOMMENDATIONS (UX only).',
    dependencies: ['capability.recommendations'],
    featureFlag: 'capabilityRecommendations',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/CapabilityRecommendationsPage.test.tsx'],
    documentation: ['docs/ui.md', 'docs/capability-recommendations.md'],
  }),
  defineCapability({
    name: 'frontend.project-planning',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Project planning wizard. Nav is gated by FEATURE_PROJECT_PLANNING (UX only).',
    dependencies: ['project.planning'],
    featureFlag: 'projectPlanning',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/ProjectPlanningPage.test.tsx'],
    documentation: ['docs/ui.md', 'docs/project-planning.md'],
  }),
  defineCapability({
    name: 'frontend.project-generator',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Project generator UI. Nav is gated by FEATURE_PROJECT_GENERATOR (UX only).',
    dependencies: ['project.generator'],
    featureFlag: 'projectGenerator',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/ProjectGeneratorPage.test.tsx'],
    documentation: ['docs/ui.md', 'docs/project-generator.md'],
  }),
  defineCapability({
    name: 'frontend.realtime',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Optional SSE client and live status UI. Nav is gated by FEATURE_REALTIME (UX only).',
    dependencies: ['realtime'],
    featureFlag: 'realtime',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/RealtimePage.test.tsx', 'frontend/src/services/realtime.test.ts'],
    documentation: ['docs/ui.md', 'docs/realtime.md'],
  }),
  defineCapability({
    name: 'frontend.search',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Keyword and full-text search UI. Nav is gated by FEATURE_SEARCH (UX only).',
    dependencies: ['search'],
    featureFlag: 'search',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/SearchPage.test.tsx'],
    documentation: ['docs/ui.md', 'docs/search.md'],
  }),
  defineCapability({
    name: 'frontend.analytics',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'KPI, time-series, dashboard, filter, and export UI. Nav is gated by FEATURE_ANALYTICS (UX only).',
    dependencies: ['analytics'],
    featureFlag: 'analytics',
    defaultEnabled: false,
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/pages/AnalyticsPage.test.tsx'],
    documentation: ['docs/ui.md', 'docs/analytics.md'],
  }),
  defineCapability({
    name: 'frontend.theme',
    kind: 'application',
    category: 'frontend',
    maturity: 'stable',
    summary: 'Light/dark/system theme, toast stack, and shared API client.',
    frontendAvailability: true,
    backendAvailability: false,
    tests: ['frontend/src/ui/cn.test.ts', 'frontend/src/services/api.test.ts'],
    documentation: ['docs/ui.md'],
  }),
];
