import { defineCapability } from './define';

export const INFRASTRUCTURE_CAPABILITIES = [
  defineCapability({
    name: 'infrastructure.postgres',
    kind: 'infrastructure',
    category: 'infrastructure',
    maturity: 'stable',
    summary: 'PostgreSQL 16 used by Prisma. The only application database.',
    environmentRequirements: ['DATABASE_URL'],
    infrastructureRequirements: ['postgres'],
    databaseRequirement: true,
    tests: ['backend/src/lib/prisma-url.test.ts'],
    documentation: ['docs/database.md', 'docs/docker.md'],
  }),
  defineCapability({
    name: 'infrastructure.redis',
    kind: 'infrastructure',
    category: 'infrastructure',
    maturity: 'stable',
    summary: 'Optional locally; required in production for cache, rate limits, OTP, idempotency, and BullMQ.',
    environmentRequirements: ['REDIS_URL'],
    infrastructureRequirements: ['redis'],
    defaultEnabled: false,
    tests: ['backend/src/lib/kv.test.ts'],
    documentation: ['docs/redis.md'],
  }),
  defineCapability({
    name: 'infrastructure.docker',
    kind: 'infrastructure',
    category: 'infrastructure',
    maturity: 'stable',
    summary: 'Compose stack for frontend, backend, worker, Postgres, and Redis.',
    infrastructureRequirements: ['docker'],
    tests: ['backend/tests/infra/docker.test.ts'],
    documentation: ['docs/docker.md'],
  }),
  defineCapability({
    name: 'infrastructure.github-actions',
    kind: 'infrastructure',
    category: 'infrastructure',
    maturity: 'stable',
    summary: 'Reusable GitHub Actions CI and provider-agnostic CD.',
    tests: ['.github/workflows/ci.yml'],
    documentation: ['docs/ci-cd.md'],
  }),
  defineCapability({
    name: 'infrastructure.nginx',
    kind: 'infrastructure',
    category: 'infrastructure',
    maturity: 'stable',
    summary: 'Optional Compose profile reverse proxy. Not started by docker compose up.',
    infrastructureRequirements: ['docker', 'nginx'],
    defaultEnabled: false,
    tests: ['backend/tests/infra/docker.test.ts'],
    documentation: ['docs/docker.md'],
  }),
];
