import { defineCapability } from './define';
import { DEFAULT_ARCHITECTURE_MODE, DEFAULT_DEPLOYMENT_MODES } from '../types';

export const MODE_CAPABILITIES = [
  defineCapability({
    name: DEFAULT_ARCHITECTURE_MODE,
    kind: 'architecture-mode',
    category: 'architecture',
    maturity: 'stable',
    summary: 'Default architecture: one Express API and one worker process sharing PostgreSQL.',
    conflicts: ['architecture.microservices'],
    architectureCompatibility: [DEFAULT_ARCHITECTURE_MODE],
    deploymentCompatibility: [...DEFAULT_DEPLOYMENT_MODES],
    tests: ['backend/src/jobs/queue.test.ts'],
    documentation: ['ARCHITECTURE.md', 'ARCHITECTURE_DECISION.md'],
  }),
  defineCapability({
    name: 'architecture.microservices',
    kind: 'architecture-mode',
    category: 'architecture',
    maturity: 'experimental',
    summary: 'Not implemented. Kit policy keeps a modular monolith; do not split extra Node services.',
    conflicts: [DEFAULT_ARCHITECTURE_MODE],
    architectureCompatibility: ['architecture.microservices'],
    deploymentCompatibility: ['deployment.kubernetes'],
    defaultEnabled: false,
    tests: ['ARCHITECTURE_DECISION.md'],
    documentation: ['ARCHITECTURE_DECISION.md', 'ARCHITECTURE.md'],
  }),
  defineCapability({
    name: 'deployment.local-hybrid',
    kind: 'deployment-mode',
    category: 'deployment',
    maturity: 'stable',
    summary: 'Host npm run dev with optional Compose Postgres/Redis (npm run deps:up).',
    architectureCompatibility: [DEFAULT_ARCHITECTURE_MODE],
    deploymentCompatibility: ['deployment.local-hybrid'],
    tests: ['docs/getting-started.md'],
    documentation: ['docs/getting-started.md', 'docs/docker.md'],
  }),
  defineCapability({
    name: 'deployment.docker-compose',
    kind: 'deployment-mode',
    category: 'deployment',
    maturity: 'stable',
    summary: 'Full Compose stack: frontend, backend, worker, Postgres, Redis, optional nginx.',
    architectureCompatibility: [DEFAULT_ARCHITECTURE_MODE],
    deploymentCompatibility: ['deployment.docker-compose'],
    infrastructureRequirements: ['docker'],
    tests: ['backend/tests/infra/docker.test.ts'],
    documentation: ['docs/docker.md'],
  }),
  defineCapability({
    name: 'deployment.kubernetes',
    kind: 'deployment-mode',
    category: 'deployment',
    maturity: 'experimental',
    summary: 'Not implemented. Kubernetes, Helm, and Terraform are out of the default kit.',
    architectureCompatibility: [DEFAULT_ARCHITECTURE_MODE, 'architecture.microservices'],
    deploymentCompatibility: ['deployment.kubernetes'],
    defaultEnabled: false,
    tests: ['ARCHITECTURE_DECISION.md'],
    documentation: ['ARCHITECTURE_DECISION.md', 'docs/docker.md'],
  }),
];
