import { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';

import { useAuth } from '@/auth/AuthProvider';
import { Badge, Breadcrumb, DataTable, EmptyState, ErrorState, LoadingState, PageContainer } from '@/ui';

import { billingTone, formatDate, formatMoney } from './format';
import { DealflowGate } from './components';
import { useQuotes } from './hooks';
import type { BillingSchedule, QuoteView } from './types';

interface ScheduleRow {
  id: string;
  quote: QuoteView;
  schedule: BillingSchedule;
  product: string;
}

function useScheduleRows(kind: 'one_time' | 'recurring') {
  const { accessToken } = useAuth();
  const quotes = useQuotes(accessToken);
  const rows = useMemo<ScheduleRow[]>(() => {
    return (quotes.data ?? []).flatMap((quote) =>
      (quote.billing ?? [])
        .filter((item) => item.billingType === kind)
        .map((schedule) => ({
          id: schedule.id,
          quote,
          schedule,
          product: quote.lines.find((line) => line.id === schedule.quoteLineId)?.product?.name ?? 'Line',
        })),
    );
  }, [kind, quotes.data]);
  return { quotes, rows };
}

export function SubscriptionsPage() {
  const navigate = useNavigate();
  const { quotes, rows } = useScheduleRows('recurring');
  return (
    <DealflowGate permission="dealflow.quotes.read">
      <PageContainer
        width="wide"
        breadcrumb={<Breadcrumb items={[{ label: 'Dashboard', to: '/dealflow' }, { label: 'Subscriptions' }]} />}
        title="Subscriptions"
        description="Recurring billing schedules generated by the DealFlow360 billing engine."
      >
        {quotes.loading ? <LoadingState label="Loading subscriptions…" /> : null}
        {quotes.error ? <ErrorState message={quotes.error} onRetry={() => void quotes.reload()} /> : null}
        {!quotes.loading && !quotes.error ? (
          <DataTable<ScheduleRow>
            caption="Recurring schedules"
            rowId={(row) => row.id}
            rows={rows}
            onRowClick={(row) => navigate(`/dealflow/quotes/${row.quote.id}?tab=billing`)}
            emptyTitle="No recurring schedules"
            emptyDescription="Generate billing on a quote that includes software or services."
            columns={[
              { id: 'quote', header: 'Quote', accessor: (row) => row.quote.number },
              { id: 'customer', header: 'Customer', accessor: (row) => row.quote.customer?.name ?? '—' },
              { id: 'product', header: 'Plan', accessor: (row) => row.product },
              { id: 'cycle', header: 'Cycle', accessor: (row) => row.schedule.frequency ?? '—' },
              { id: 'amount', header: 'Amount', accessor: (row) => formatMoney(row.schedule.amount, true) },
              { id: 'next', header: 'Next billing', accessor: (row) => formatDate(row.schedule.nextBillingAt) },
              {
                id: 'status',
                header: 'Status',
                accessor: (row) => <Badge tone={billingTone(row.schedule.status)}>{row.schedule.status}</Badge>,
              },
            ]}
          />
        ) : null}
      </PageContainer>
    </DealflowGate>
  );
}

export function InvoicesPage() {
  const navigate = useNavigate();
  const { quotes, rows } = useScheduleRows('one_time');
  return (
    <DealflowGate permission="dealflow.quotes.read">
      <PageContainer
        width="wide"
        breadcrumb={<Breadcrumb items={[{ label: 'Dashboard', to: '/dealflow' }, { label: 'Invoices' }]} />}
        title="Invoices"
        description="One-time invoices from generated billing schedules. The API does not collect or record payments."
      >
        {quotes.loading ? <LoadingState label="Loading invoices…" /> : null}
        {quotes.error ? <ErrorState message={quotes.error} onRetry={() => void quotes.reload()} /> : null}
        {!quotes.loading && !quotes.error ? (
          rows.length === 0 ? (
            <EmptyState title="No one-time invoices" description="Confirm a hardware line and generate billing." />
          ) : (
            <DataTable<ScheduleRow>
              caption="One-time invoices"
              rowId={(row) => row.id}
              rows={rows}
              onRowClick={(row) => navigate(`/dealflow/quotes/${row.quote.id}?tab=billing`)}
              emptyTitle="No invoices"
              columns={[
                { id: 'number', header: 'Quote', accessor: (row) => row.quote.number },
                { id: 'customer', header: 'Customer', accessor: (row) => row.quote.customer?.name ?? '—' },
                { id: 'product', header: 'Line', accessor: (row) => row.product },
                { id: 'amount', header: 'Amount', accessor: (row) => formatMoney(row.schedule.amount, true) },
                { id: 'type', header: 'Type', accessor: () => 'One-time' },
                {
                  id: 'status',
                  header: 'Status',
                  accessor: (row) => <Badge tone={billingTone(row.schedule.status)}>{row.schedule.status}</Badge>,
                },
              ]}
            />
          )
        ) : null}
      </PageContainer>
    </DealflowGate>
  );
}
