import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { useAuth } from '@/auth/AuthProvider';
import { hasPermission } from '@/lib/rbac';
import { getApiErrorMessage } from '@/services/api';
import { Badge, Breadcrumb, DataTable, EmptyState, ErrorState, LoadingState, PageContainer, useToast } from '@/ui';

import { cancelBilling } from './api';
import { billingTone, formatDate, formatMoney } from './format';
import { DealflowGate, editRecordItem, RecordMenu } from './components';
import { useQuotes } from './hooks';
import type { BillingSchedule, BillingStatus, QuoteView } from './types';

interface ScheduleRow {
  id: string;
  quote: QuoteView;
  schedule: BillingSchedule;
  product: string;
}

function useScheduleRows(kind: 'one_time' | 'recurring') {
  const { accessToken } = useAuth();
  const quotes = useQuotes(accessToken);
  const rows = useMemo<ScheduleRow[]>(() => {
    return (quotes.data ?? []).flatMap((quote) =>
      (quote.billing ?? [])
        .filter((item) => item.billingType === kind)
        .map((schedule) => ({
          id: schedule.id,
          quote,
          schedule,
          product: quote.lines.find((line) => line.id === schedule.quoteLineId)?.product?.name ?? 'Line',
        })),
    );
  }, [kind, quotes.data]);
  return { quotes, rows };
}

function StatusFilters({
  value,
  onChange,
  label,
}: {
  value: 'all' | BillingStatus;
  onChange: (value: 'all' | BillingStatus) => void;
  label: string;
}) {
  return (
    <div className="mb-5 flex flex-wrap gap-2" role="tablist" aria-label={label}>
      {(
        [
          { id: 'all', label: 'All' },
          { id: 'scheduled', label: 'Scheduled' },
          { id: 'invoiced', label: 'Invoiced' },
          { id: 'cancelled', label: 'Cancelled' },
        ] as const
      ).map((item) => {
        const active = value === item.id;
        return (
          <button
            key={item.id}
            type="button"
            role="tab"
            aria-selected={active}
            className={`rounded-full border px-3 py-1.5 text-caption transition-colors duration-df ${
              active
                ? 'border-foreground bg-foreground text-foreground-inverted'
                : 'border-edge text-foreground-muted hover:border-foreground/30 hover:text-foreground'
            }`}
            onClick={() => onChange(item.id)}
          >
            {item.label}
          </button>
        );
      })}
    </div>
  );
}

export function SubscriptionsPage() {
  const navigate = useNavigate();
  const { accessToken, user } = useAuth();
  const { toast } = useToast();
  const { quotes, rows } = useScheduleRows('recurring');
  const [status, setStatus] = useState<'all' | BillingStatus>('all');
  const visible = status === 'all' ? rows : rows.filter((row) => row.schedule.status === status);
  return (
    <DealflowGate permission="dealflow.quotes.read">
      <PageContainer
        width="wide"
        breadcrumb={<Breadcrumb items={[{ label: 'Dashboard', to: '/dealflow' }, { label: 'Subscriptions' }]} />}
        title="Subscriptions"
        description="Recurring billing schedules generated by the DealFlow360 billing engine. There is no expired status — cancelled schedules stay cancelled."
      >
        <StatusFilters value={status} onChange={setStatus} label="Subscription status" />
        {quotes.loading ? <LoadingState label="Loading subscriptions…" /> : null}
        {quotes.error ? <ErrorState message={quotes.error} onRetry={() => void quotes.reload()} /> : null}
        {!quotes.loading && !quotes.error ? (
          <DataTable<ScheduleRow>
            caption="Recurring schedules"
            rowId={(row) => row.id}
            rows={visible}
            onRowClick={(row) => navigate(`/dealflow/subscriptions/${row.quote.id}`)}
            emptyTitle="No recurring schedules"
            emptyDescription="Generate billing on a quote that includes software or services."
            columns={[
              { id: 'quote', header: 'Quote', accessor: (row) => row.quote.number },
              { id: 'customer', header: 'Customer', accessor: (row) => row.quote.customer?.name ?? '—' },
              { id: 'product', header: 'Plan', accessor: (row) => row.product },
              { id: 'cycle', header: 'Cycle', accessor: (row) => row.schedule.frequency ?? '—' },
              { id: 'amount', header: 'Amount', accessor: (row) => formatMoney(row.schedule.amount, true) },
              { id: 'next', header: 'Next billing', accessor: (row) => formatDate(row.schedule.nextBillingAt) },
              {
                id: 'status',
                header: 'Status',
                accessor: (row) => <Badge tone={billingTone(row.schedule.status)}>{row.schedule.status}</Badge>,
              },
              {
                id: 'actions',
                header: '',
                accessor: (row) =>
                  hasPermission(user, 'dealflow.billing.write') && row.schedule.status !== 'cancelled' ? (
                    <RecordMenu
                      items={[
                        editRecordItem(`Open ${row.quote.number} billing.`, () =>
                          navigate(`/dealflow/quotes/${row.quote.id}?tab=billing`),
                        ),
                        {
                          id: 'cancel',
                          label: 'Delete 🗑️',
                          description: `Cancel this subscription schedule on ${row.quote.number}. Generated invoices are not hard-deleted; cancel preserves history.`,
                          confirmLabel: 'Cancel schedule',
                          destructive: true,
                          onConfirm: async () => {
                            if (!accessToken) return;
                            try {
                              await cancelBilling(row.quote.id, row.schedule.id, accessToken, row.quote.version);
                              toast({ title: 'Subscription cancelled', variant: 'success' });
                              await quotes.reload();
                            } catch (caught) {
                              toast({ title: getApiErrorMessage(caught, 'Schedule could not be cancelled'), variant: 'error' });
                            }
                          },
                        },
                      ]}
                    />
                  ) : null,
              },
            ]}
          />
        ) : null}
      </PageContainer>
    </DealflowGate>
  );
}

export function InvoicesPage() {
  const navigate = useNavigate();
  const { accessToken, user } = useAuth();
  const { toast } = useToast();
  const { quotes, rows } = useScheduleRows('one_time');
  const [status, setStatus] = useState<'all' | BillingStatus>('all');
  const visible = status === 'all' ? rows : rows.filter((row) => row.schedule.status === status);
  return (
    <DealflowGate permission="dealflow.quotes.read">
      <PageContainer
        width="wide"
        breadcrumb={<Breadcrumb items={[{ label: 'Dashboard', to: '/dealflow' }, { label: 'Invoices' }]} />}
        title="Invoices"
        description="One-time invoices from generated billing schedules. The API does not collect or record payments."
      >
        <StatusFilters value={status} onChange={setStatus} label="Invoice status" />
        {quotes.loading ? <LoadingState label="Loading invoices…" /> : null}
        {quotes.error ? <ErrorState message={quotes.error} onRetry={() => void quotes.reload()} /> : null}
        {!quotes.loading && !quotes.error ? (
          visible.length === 0 ? (
            <EmptyState title="No one-time invoices" description="Confirm a hardware line and generate billing." />
          ) : (
            <DataTable<ScheduleRow>
              caption="One-time invoices"
              rowId={(row) => row.id}
              rows={visible}
              onRowClick={(row) => navigate(`/dealflow/invoices/${row.quote.id}`)}
              emptyTitle="No invoices"
              columns={[
                { id: 'number', header: 'Quote', accessor: (row) => row.quote.number },
                { id: 'customer', header: 'Customer', accessor: (row) => row.quote.customer?.name ?? '—' },
                { id: 'product', header: 'Line', accessor: (row) => row.product },
                { id: 'amount', header: 'Amount', accessor: (row) => formatMoney(row.schedule.amount, true) },
                { id: 'type', header: 'Type', accessor: () => 'One-time' },
                {
                  id: 'status',
                  header: 'Status',
                  accessor: (row) => <Badge tone={billingTone(row.schedule.status)}>{row.schedule.status}</Badge>,
                },
                {
                  id: 'actions',
                  header: '',
                  accessor: (row) =>
                    hasPermission(user, 'dealflow.billing.write') && row.schedule.status !== 'cancelled' ? (
                      <RecordMenu
                        items={[
                          editRecordItem(`Open ${row.quote.number} invoice workspace.`, () =>
                            navigate(`/dealflow/quotes/${row.quote.id}?tab=billing`),
                          ),
                          {
                            id: 'cancel',
                            label: 'Delete 🗑️',
                            description: `Cancel this invoice schedule on ${row.quote.number}. Generated invoices are not hard-deleted; cancel preserves history.`,
                            confirmLabel: 'Cancel invoice',
                            destructive: true,
                            onConfirm: async () => {
                              if (!accessToken) return;
                              try {
                                await cancelBilling(row.quote.id, row.schedule.id, accessToken, row.quote.version);
                                toast({ title: 'Invoice cancelled', variant: 'success' });
                                await quotes.reload();
                              } catch (caught) {
                                toast({ title: getApiErrorMessage(caught, 'Invoice could not be cancelled'), variant: 'error' });
                              }
                            },
                          },
                        ]}
                      />
                    ) : null,
                },
              ]}
            />
          )
        ) : null}
      </PageContainer>
    </DealflowGate>
  );
}
