import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';

import { useAuth } from '@/auth/AuthProvider';
import { hasPermission } from '@/lib/rbac';
import { getApiErrorMessage } from '@/services/api';
import { Badge, Breadcrumb, Button, Card, CardTitle, EmptyState, ErrorState, LoadingState, PageContainer, useToast } from '@/ui';

import { cancelBilling, downloadCustomerQuotePdf, generateBilling } from './api';
import { DealflowGate, RecordMenu, StatusBadge } from './components';
import { billingTone, canBill, formatDate, formatMoney } from './format';
import { useQuote } from './hooks';
import type { BillingSchedule, BillingType, QuoteView } from './types';

function useCommercialQuote() {
  const { quoteId } = useParams<{ quoteId: string }>();
  const { accessToken, user } = useAuth();
  const quoteState = useQuote(quoteId, accessToken);
  const [busy, setBusy] = useState(false);
  const { toast } = useToast();

  async function run(action: () => Promise<QuoteView>, title: string) {
    if (!accessToken) return;
    setBusy(true);
    try {
      quoteState.setQuote(await action());
      toast({ title, variant: 'success' });
    } catch (caught) {
      toast({ title: getApiErrorMessage(caught, 'Billing update failed'), variant: 'error' });
    } finally {
      setBusy(false);
    }
  }

  return { accessToken, user, quoteState, quote: quoteState.data, busy, run, toast };
}

function ScheduleList({
  quote,
  kind,
  emptyTitle,
  canCancel,
  onCancel,
}: {
  quote: QuoteView;
  kind: BillingType;
  emptyTitle: string;
  canCancel: boolean;
  onCancel: (schedule: BillingSchedule) => void;
}) {
  const rows = quote.billing.filter((item) => item.billingType === kind);
  if (rows.length === 0) {
    return <EmptyState title={emptyTitle} description="Generate billing after the quote is approved or confirmed." />;
  }
  return (
    <ul className="space-y-3">
      {rows.map((item) => {
        const line = quote.lines.find((row) => row.id === item.quoteLineId);
        return (
          <li key={item.id} className="rounded-lg border border-edge p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <p className="font-medium">{line?.product?.name ?? 'Line'}</p>
                <p className="text-caption text-foreground-muted">
                  {formatMoney(item.amount, true)} · {item.frequency ?? 'one-time'}
                  {item.nextBillingAt ? ` · next ${formatDate(item.nextBillingAt)}` : ''}
                </p>
              </div>
              <Badge tone={billingTone(item.status)}>{item.status}</Badge>
            </div>
            {canCancel && item.status !== 'cancelled' ? (
              <div className="mt-3">
                <RecordMenu
                  buttonLabel="Cancel"
                  items={[
                    {
                      id: 'cancel',
                      label: 'Delete 🗑️',
                      description: 'Cancel this billing schedule. Generated invoices are not hard-deleted; cancel preserves history.',
                      confirmLabel: 'Cancel schedule',
                      destructive: true,
                      onConfirm: () => onCancel(item),
                    },
                  ]}
                />
              </div>
            ) : null}
          </li>
        );
      })}
    </ul>
  );
}

export function BillingDetailPage() {
  const navigate = useNavigate();
  const { accessToken, user, quoteState, quote, busy, run } = useCommercialQuote();

  return (
    <DealflowGate permission="dealflow.quotes.read">
      <PageContainer
        width="wide"
        breadcrumb={
          <Breadcrumb
            items={[
              { label: 'Dashboard', to: '/dealflow' },
              { label: 'Subscriptions', to: '/dealflow/subscriptions' },
              { label: quote?.number ?? 'Billing' },
            ]}
          />
        }
        title={quote ? `${quote.number} · ${quote.customer.name}` : 'Billing detail'}
        description="One-time and recurring schedules generated by the DealFlow billing engine. The API does not collect payments."
        actions={
          quote ? (
            <Button variant="outline" onClick={() => navigate(`/dealflow/quotes/${quote.id}?tab=billing`)}>
              Open workspace
            </Button>
          ) : null
        }
      >
        {quoteState.loading ? <LoadingState label="Loading billing…" /> : null}
        {quoteState.error ? <ErrorState message={quoteState.error} onRetry={() => void quoteState.reload()} /> : null}
        {quote ? (
          <div className="space-y-6">
            <div className="flex flex-wrap items-center gap-3">
              <StatusBadge status={quote.status} />
              <Link className="text-sm font-medium hover:underline" to={`/dealflow/invoices/${quote.id}`}>
                One-time invoices
              </Link>
              <Link className="text-sm font-medium hover:underline" to={`/portal/${encodeURIComponent(quote.portalToken)}`}>
                Customer portal
              </Link>
            </div>
            <div className="grid gap-6 lg:grid-cols-2">
              <Card>
                <CardTitle>One-time / up-front</CardTitle>
                <div className="mt-4">
                  <ScheduleList
                    quote={quote}
                    kind="one_time"
                    emptyTitle="No one-time invoice"
                    canCancel={hasPermission(user, 'dealflow.billing.write')}
                    onCancel={(schedule) =>
                      accessToken &&
                      void run(
                        () => cancelBilling(quote.id, schedule.id, accessToken, quote.version),
                        'Schedule cancelled',
                      )
                    }
                  />
                </div>
              </Card>
              <Card>
                <CardTitle>Recurring</CardTitle>
                <div className="mt-4">
                  <ScheduleList
                    quote={quote}
                    kind="recurring"
                    emptyTitle="No subscription schedule"
                    canCancel={hasPermission(user, 'dealflow.billing.write')}
                    onCancel={(schedule) =>
                      accessToken &&
                      void run(
                        () => cancelBilling(quote.id, schedule.id, accessToken, quote.version),
                        'Schedule cancelled',
                      )
                    }
                  />
                </div>
              </Card>
            </div>
            {canBill(quote.status) && hasPermission(user, 'dealflow.billing.write') ? (
              <Button
                loading={busy}
                onClick={() =>
                  accessToken && void run(() => generateBilling(quote.id, accessToken, quote.version), 'Billing generated')
                }
              >
                Generate billing
              </Button>
            ) : null}
          </div>
        ) : null}
      </PageContainer>
    </DealflowGate>
  );
}

export function InvoiceDetailPage() {
  const navigate = useNavigate();
  const { accessToken, user, quoteState, quote, busy, run, toast } = useCommercialQuote();
  const invoices = quote?.billing.filter((item) => item.billingType === 'one_time') ?? [];

  return (
    <DealflowGate permission="dealflow.quotes.read">
      <PageContainer
        width="wide"
        breadcrumb={
          <Breadcrumb
            items={[
              { label: 'Dashboard', to: '/dealflow' },
              { label: 'Invoices', to: '/dealflow/invoices' },
              { label: quote?.number ?? 'Invoice' },
            ]}
          />
        }
        title={quote ? `${quote.number} · ${quote.customer.name}` : 'Invoice detail'}
        description="Commercial invoice view of generated one-time schedules. Payment collection is not implemented."
        actions={
          quote ? (
            <Button variant="outline" onClick={() => navigate(`/dealflow/quotes/${quote.id}?tab=billing`)}>
              Open workspace
            </Button>
          ) : null
        }
      >
        {quoteState.loading ? <LoadingState label="Loading invoice…" /> : null}
        {quoteState.error ? <ErrorState message={quoteState.error} onRetry={() => void quoteState.reload()} /> : null}
        {quote ? (
          <div className="space-y-6">
            <ol className="grid gap-2 sm:grid-cols-3">
              {(() => {
                const current =
                  invoices.some((item) => item.status === 'invoiced')
                    ? 'invoiced'
                    : invoices.some((item) => item.status === 'scheduled')
                      ? 'scheduled'
                      : 'draft';
                return (['draft', 'scheduled', 'invoiced'] as const).map((step) => (
                  <li
                    key={step}
                    className={`rounded-lg border px-3 py-2 text-sm capitalize ${
                      current === step ? 'border-accent bg-surface-muted' : 'border-edge text-foreground-muted'
                    }`}
                  >
                    {step === 'draft' ? 'Not generated' : step}
                  </li>
                ));
              })()}
            </ol>
            <section className="rounded-lg border border-edge p-5">
              <p className="text-caption text-foreground-muted">{quote.number}</p>
              <h2 className="mt-1 text-title">{quote.customer.name}</h2>
              <p className="mt-4 text-[28px] font-semibold tracking-tight">{formatMoney(quote.grandTotal ?? quote.netTotal, true)}</p>
              <p className="text-caption text-foreground-muted">
                Net {formatMoney(quote.netTotal, true)} · Tax {formatMoney(quote.taxTotal ?? 0, true)}
              </p>
              <ul className="mt-6 divide-y divide-edge">
                {quote.lines.map((line) => (
                  <li key={line.id} className="flex flex-wrap justify-between gap-3 py-3 text-sm">
                    <span>
                      {line.product?.name ?? line.productId} · qty {line.quantity}
                    </span>
                    <span>{formatMoney((line.listPrice * line.quantity * (100 - line.discountPercent)) / 100, true)}</span>
                  </li>
                ))}
              </ul>
            </section>
            <ScheduleList
              quote={quote}
              kind="one_time"
              emptyTitle="No one-time invoice"
              canCancel={hasPermission(user, 'dealflow.billing.write')}
              onCancel={(schedule) =>
                accessToken &&
                void run(() => cancelBilling(quote.id, schedule.id, accessToken, quote.version), 'Invoice cancelled')
              }
            />
            <div className="flex flex-wrap gap-2">
              {canBill(quote.status) && hasPermission(user, 'dealflow.billing.write') ? (
                <Button
                  loading={busy}
                  onClick={() =>
                    accessToken && void run(() => generateBilling(quote.id, accessToken, quote.version), 'Billing generated')
                  }
                >
                  Generate billing
                </Button>
              ) : null}
              <Button
                variant="outline"
                loading={busy}
                onClick={() => {
                  if (!accessToken) return;
                  void downloadCustomerQuotePdf(quote.id, accessToken).catch((caught: unknown) => {
                    toast({ title: getApiErrorMessage(caught, 'PDF download failed'), variant: 'error' });
                  });
                }}
              >
                Download customer PDF
              </Button>
              <Link
                className="inline-flex h-10 items-center rounded-control border border-edge px-3.5 text-sm font-medium hover:bg-surface-muted"
                to={`/portal/${encodeURIComponent(quote.portalToken)}`}
              >
                Share customer portal
              </Link>
              <Link
                className="inline-flex h-10 items-center rounded-control border border-edge px-3.5 text-sm font-medium hover:bg-surface-muted"
                to="/dealflow/health"
              >
                Deal health
              </Link>
            </div>
          </div>
        ) : null}
      </PageContainer>
    </DealflowGate>
  );
}
