import type { AuthSession } from '@/auth/AuthProvider';

import type { QuoteView } from './types';

export const CUSTOMER_SESSION: AuthSession = {
  accessToken: 'customer-token',
  refreshToken: 'customer-refresh',
  user: {
    id: '00000000-0000-4000-8000-0000000000a4',
    email: 'demo.user@example.com',
    displayName: 'Demo User',
    status: 'active',
    role: 'user',
    roles: ['user'],
    permissions: ['notifications.read'],
  },
};

export const STAFF_SESSION: AuthSession = {
  accessToken: 'test-token',
  refreshToken: 'refresh-token',
  user: {
    id: '00000000-0000-4000-8000-0000000000a1',
    email: 'demo.staff@example.com',
    displayName: 'Demo Staff',
    status: 'active',
    role: 'staff',
    roles: ['staff'],
    permissions: [
      'dealflow.catalog.read',
      'dealflow.catalog.products.write',
      'dealflow.quotes.read',
      'dealflow.quotes.write',
      'dealflow.fulfillment.write',
      'dealflow.billing.write',
    ],
  },
};

export const SAMPLE_QUOTE: QuoteView = {
  id: 'ad86fcdd-202b-4b6b-a14e-a1c88ad5a3b5',
  number: 'DF-00002',
  customerId: '11111111-1111-4111-8111-111111111111',
  ownerId: STAFF_SESSION.user.id,
  status: 'approval_required',
  listTotal: 34400,
  discountTotal: 5504,
  netTotal: 28896,
  costTotal: 18000,
  marginPercent: 37.7,
  blendedDiscountPercent: 16,
  riskScore: 80.95,
  assessmentDecision: 'approval_required',
  requiredChainId: 'ddddddd1-dddd-4ddd-8ddd-ddddddddddd3',
  portalToken: 'portal-token-northwind-live',
  version: 1,
  createdAt: '2026-09-05T05:00:00.000Z',
  updatedAt: '2026-09-05T05:10:00.000Z',
  customer: {
    id: '11111111-1111-4111-8111-111111111111',
    name: 'Northwind Retail',
    email: 'procurement@northwind.example',
    tier: 'standard',
  },
  lines: [
    {
      id: 'line-hw',
      quoteId: 'ad86fcdd-202b-4b6b-a14e-a1c88ad5a3b5',
      productId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
      quantity: 8,
      listPrice: 4000,
      discountPercent: 16,
      unitCost: 2200,
      product: {
        id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
        sku: 'HW-CORE-1',
        name: 'Core Gateway',
        category: 'hardware',
        listPrice: 4000,
        cost: 2200,
        billingType: 'one_time',
      },
    },
  ],
  assessment: {
    decision: 'approval_required',
    blendedDiscountPercent: 16,
    riskScore: 80.95,
    listTotal: 34400,
    discountTotal: 5504,
    netTotal: 28896,
    costTotal: 18000,
    marginPercent: 37.7,
    warningCount: 0,
    approvalLineCount: 1,
    rejectedCount: 0,
    cumulativeEscalated: false,
    requiredChainName: 'Sales Manager → Finance → Final',
    lines: [
      {
        lineId: 'line-hw',
        productId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
        sku: 'HW-CORE-1',
        quantity: 8,
        discountPercent: 16,
        listAmount: 32000,
        netAmount: 26880,
        costAmount: 17600,
        marginPercent: 34.5,
        marginErosionPercent: 12,
        policyId: 'ccccccc1-cccc-4ccc-8ccc-ccccccccccc4',
        policyName: 'Default ceiling',
        decision: 'approval_required',
        reasons: ['Requested 16% exceeds approval ceiling 5% (Default ceiling)'],
      },
    ],
    reasons: ['Requested 16% exceeds approval ceiling 5% (Default ceiling)'],
  },
  approvals: [
    {
      id: 'apr-1',
      quoteId: 'ad86fcdd-202b-4b6b-a14e-a1c88ad5a3b5',
      chainId: 'chain-1',
      stepOrder: 1,
      roleKey: 'manager',
      label: 'Sales Manager',
      status: 'pending',
    },
  ],
  fulfillment: { allocations: [], backorders: [], shipmentCount: 0, fulfillmentCost: 0, backorderQuantity: 0 },
  billing: [],
  revisions: [],
};
